import type { ModelInfo } from "../types/model.js";

export const builtInModels: ModelInfo[] = [
  // ── OpenAI ──────────────────────────────────────────────
  {
    provider: "openai",
    modelId: "gpt-4o",
    displayName: "GPT-4o",
    contextWindowSize: 128_000,
    inputCostPer1MTokens: 2.5,
    outputCostPer1MTokens: 10,
    cacheReadCostPer1MTokens: 1.25,
    capabilities: {
      supportsReasoning: false,
      supportsToolCalls: true,
      supportsStreaming: true,
      supportsImages: true,
      contextWindowSize: 128_000,
    },
  },
  {
    provider: "openai",
    modelId: "gpt-4o-mini",
    displayName: "GPT-4o mini",
    contextWindowSize: 128_000,
    inputCostPer1MTokens: 0.15,
    outputCostPer1MTokens: 0.6,
    cacheReadCostPer1MTokens: 0.075,
    capabilities: {
      supportsReasoning: false,
      supportsToolCalls: true,
      supportsStreaming: true,
      supportsImages: true,
      contextWindowSize: 128_000,
    },
  },
  {
    provider: "openai",
    modelId: "o3",
    displayName: "o3",
    contextWindowSize: 200_000,
    inputCostPer1MTokens: 10,
    outputCostPer1MTokens: 40,
    cacheReadCostPer1MTokens: 2.5,
    capabilities: {
      supportsReasoning: true,
      supportsToolCalls: true,
      supportsStreaming: true,
      supportsImages: true,
      contextWindowSize: 200_000,
    },
  },
  {
    provider: "openai",
    modelId: "o3-mini",
    displayName: "o3 mini",
    contextWindowSize: 200_000,
    inputCostPer1MTokens: 1.1,
    outputCostPer1MTokens: 4.4,
    cacheReadCostPer1MTokens: 0.55,
    capabilities: {
      supportsReasoning: true,
      supportsToolCalls: true,
      supportsStreaming: true,
      supportsImages: false,
      contextWindowSize: 200_000,
    },
  },
  {
    provider: "openai",
    modelId: "o4-mini",
    displayName: "o4 mini",
    contextWindowSize: 200_000,
    inputCostPer1MTokens: 1.1,
    outputCostPer1MTokens: 4.4,
    cacheReadCostPer1MTokens: 0.55,
    capabilities: {
      supportsReasoning: true,
      supportsToolCalls: true,
      supportsStreaming: true,
      supportsImages: true,
      contextWindowSize: 200_000,
    },
  },

  // ── Anthropic ───────────────────────────────────────────
  {
    provider: "anthropic",
    modelId: "claude-sonnet-4-20250514",
    displayName: "Claude Sonnet 4",
    contextWindowSize: 200_000,
    inputCostPer1MTokens: 3,
    outputCostPer1MTokens: 15,
    cacheReadCostPer1MTokens: 0.3,
    cacheWriteCostPer1MTokens: 3.75,
    capabilities: {
      supportsReasoning: true,
      supportsToolCalls: true,
      supportsStreaming: true,
      supportsImages: true,
      contextWindowSize: 200_000,
    },
  },
  {
    provider: "anthropic",
    modelId: "claude-opus-4-20250514",
    displayName: "Claude Opus 4",
    contextWindowSize: 200_000,
    inputCostPer1MTokens: 15,
    outputCostPer1MTokens: 75,
    cacheReadCostPer1MTokens: 1.5,
    cacheWriteCostPer1MTokens: 18.75,
    capabilities: {
      supportsReasoning: true,
      supportsToolCalls: true,
      supportsStreaming: true,
      supportsImages: true,
      contextWindowSize: 200_000,
    },
  },
  {
    provider: "anthropic",
    modelId: "claude-haiku-4-20250514",
    displayName: "Claude Haiku 4",
    contextWindowSize: 200_000,
    inputCostPer1MTokens: 0.8,
    outputCostPer1MTokens: 4,
    cacheReadCostPer1MTokens: 0.08,
    cacheWriteCostPer1MTokens: 1,
    capabilities: {
      supportsReasoning: false,
      supportsToolCalls: true,
      supportsStreaming: true,
      supportsImages: true,
      contextWindowSize: 200_000,
    },
  },

  // ── Google ──────────────────────────────────────────────
  {
    provider: "google",
    modelId: "gemini-2.5-pro",
    displayName: "Gemini 2.5 Pro",
    contextWindowSize: 1_048_576,
    inputCostPer1MTokens: 1.25,
    outputCostPer1MTokens: 10,
    capabilities: {
      supportsReasoning: true,
      supportsToolCalls: true,
      supportsStreaming: true,
      supportsImages: true,
      contextWindowSize: 1_048_576,
    },
  },
  {
    provider: "google",
    modelId: "gemini-2.5-flash",
    displayName: "Gemini 2.5 Flash",
    contextWindowSize: 1_048_576,
    inputCostPer1MTokens: 0.15,
    outputCostPer1MTokens: 0.6,
    capabilities: {
      supportsReasoning: true,
      supportsToolCalls: true,
      supportsStreaming: true,
      supportsImages: true,
      contextWindowSize: 1_048_576,
    },
  },
  {
    provider: "google",
    modelId: "gemini-2.0-flash",
    displayName: "Gemini 2.0 Flash",
    contextWindowSize: 1_048_576,
    inputCostPer1MTokens: 0.1,
    outputCostPer1MTokens: 0.4,
    capabilities: {
      supportsReasoning: false,
      supportsToolCalls: true,
      supportsStreaming: true,
      supportsImages: true,
      contextWindowSize: 1_048_576,
    },
  },

  // ── Perplexity ──────────────────────────────────────────
  {
    provider: "perplexity",
    modelId: "sonar",
    displayName: "Sonar",
    contextWindowSize: 128_000,
    inputCostPer1MTokens: 1,
    outputCostPer1MTokens: 1,
    capabilities: {
      supportsReasoning: false,
      supportsToolCalls: false,
      supportsStreaming: true,
      supportsImages: false,
      contextWindowSize: 128_000,
    },
  },
  {
    provider: "perplexity",
    modelId: "sonar-pro",
    displayName: "Sonar Pro",
    contextWindowSize: 200_000,
    inputCostPer1MTokens: 3,
    outputCostPer1MTokens: 15,
    capabilities: {
      supportsReasoning: false,
      supportsToolCalls: false,
      supportsStreaming: true,
      supportsImages: false,
      contextWindowSize: 200_000,
    },
  },
  {
    provider: "perplexity",
    modelId: "sonar-reasoning",
    displayName: "Sonar Reasoning",
    contextWindowSize: 128_000,
    inputCostPer1MTokens: 1,
    outputCostPer1MTokens: 5,
    capabilities: {
      supportsReasoning: true,
      supportsToolCalls: false,
      supportsStreaming: true,
      supportsImages: false,
      contextWindowSize: 128_000,
    },
  },
  {
    provider: "perplexity",
    modelId: "sonar-reasoning-pro",
    displayName: "Sonar Reasoning Pro",
    contextWindowSize: 128_000,
    inputCostPer1MTokens: 2,
    outputCostPer1MTokens: 8,
    capabilities: {
      supportsReasoning: true,
      supportsToolCalls: false,
      supportsStreaming: true,
      supportsImages: false,
      contextWindowSize: 128_000,
    },
  },
];
